# Generated by Django 4.1.5 on 2023-01-10 01:00

from django.db import migrations, models
import django.db.models.deletion
from persons.models import DocumentTypeModel


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'document_type_tb',
            },
        ),
        migrations.CreateModel(
            name='PersonsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('hobbie', models.CharField(max_length=500)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.documenttypemodel')),
            ],
            options={
                'db_table': 'persons_tb',
            },
        ),
        migrations.RunSQL(
            "INSERT INTO public.document_type_tb (description) VALUES('CC'), ('CE'), ('TI'), ('NIT');"
        )
    ]
